# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Industries Feed"
  description: Industries feed block
  icon: work

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  body: ""
  button:
    button_url: 
    button_text:
    open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
