# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Team Intro
  description: A team intro block
  icon: handshake

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  body: >-
    ""
  team: 
    - heading: ""
      job_title: ""
      image: ""
  button:
    enabled: false
    button_url: ""
    button_text: ""
    open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
