baseURL = "https://www.keynecta.com"
languageCode = "en-us"
title = "Keynecta"
enableRobotsTXT = true
paginate = "9"
summaryLength = 20

#################### default parameters ################################

[params]
  minifyBundles = true
  imgixDomain = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[module]
replacements = "components.local -> ../component-library"

[[module.imports]]
path = 'components.local'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'

[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[[menu.main]]
  name = "Training"
  url = "/training/"
  weight = 1

[[menu.main]]
  name = "Job Specific Training Development"
  url = "/training/job-specific-training/"
  weight = 1
  parent = "Training"

[[menu.main]]
  name = "Supervisor Leadership Training"
  url = "/training/leadership-training/"
  weight = 2
  parent = "Training"

[[menu.main]]
  name = "Online OSHA Training"
  url = "/training/online-osha-training/"
  weight = 3
  parent = "Training"

[[menu.main]]
  name = "Online OSHA Compliance"
  url = "/training/online-osha-compliance/"
  weight = 4
  parent = "Training"

[[menu.main]]
  name = "Our Process"
  url = "/our-process/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Industries"
  url = "/industries/"
  weight = 4

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 5

[[menu.main]]
  name = "Client Portal"
  url = "http://portal.keynecta.com/"
  weight = 6

  [menu.main.params]
    external = true

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7