const autoprefixer = require('autoprefixer')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './layouts/**/*.svg',
        './component-library/**/*.html',
        './content/**/*.md',
      ],
      safelist: [
        'content-grid',
        'content-sm',
        'content-md',
        'content-lg',
        'content-full',
        'breakout',
        'block',
        'block-sm',
        'block-md',
        'block-lg',
        'block-xl',
        'mobile-dropdown-open',
        'is-active',
        'nav-open',
        'has-dropdown-open',
        'has-sub-menu-open',
        'expand',
        'collapse',
        'page-home',
        'page-services',
        'page-our-process',
        'page-about',
        'page-industries',
        'page-resources',
        'page-contact',
        'parent-page-services',
        'parent-page-our-process',
        'parent-page-about',
        'parent-page-industries',
        'parent-page-contact',
        'parent-page-categories',
        'parent-page-resources',
        'active-button',
        'position-open',
        'list-open',
        'toggle-mobile-dropdown',
        'ul', 
        'ol',
        'table',
        'tr',
        'td',
        'pre',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'btn--active',
        'auto-grid',
        'bg-black',
        'bg-gray',
        'bg-white',
        'text-align-start',
        'text-align-center',
        'text-align-end',
        'has-list-two-col',
        'calendly-inline-widget',
      ],
    }),
  ],
}