# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Home Hero"
  description: Hero with image grid
  icon: auto_awesome_mosaic

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  body: ""
  button:
    enabled: true
    button_url: 
    button_text:
    open_in_new_tab: false
  button_2:
    enabled: true
    button_url: 
    button_text:
    open_in_new_tab: false
  youtube_video_id:
  video_fallback_image:
    image_url:
    image_alt:
  image_1:
    image_url:
    image_alt:
  image_2:
    image_url:
    image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
