# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Bios"
  description: Staff bios block
  icon: perm_media

# Defines the structure of this component, as well as the default values
blueprint:
  bios: 
    - heading: ""
      job_title: ""
      body: ""
      image:
        image_url: ""
      background_color: white

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
